version: "2"
services:
  app:
    build: ./app
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: mysql:3306

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gitscrape
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
